- hosts: workers
  become: yes
  vars:
    pypi_reg: https://art.rd.aorti.ru/repository/pypi-proxy/simple
  tasks:
    - name: Install apt packages
      apt:
        name:
          - apt-transport-https
          - vim
          - gcc
          - make
          - autoconf
          - python3
          - python3-dev
          - python3-pip
          - libiberty-dev
          - libpq-dev
        state: present
        update_cache: true

    - name: Install pip packages
      pip:
        name:
          - docker
          - openshift
          - psycopg2
        extra_args: -i {{pypi_reg}}
